export let SET_USER_ACCOUNT = 'SET_USER_ACCOUNT';
export let SET_USER_PASSWORD = 'SET_USER_PASSWORD';
export let LOGIN_REQUEST = 'LOGIN_REQUEST';
export let LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export let LOGIN_FAIL = 'LOGIN_FAIL';

export let CONNECT_WEB_SOCKET = 'CONNECT_WEB_SOCKET';
export let CONNECT_WEB_SOCKET_SUCCESS = 'CONNECT_WEB_SOCKET_SUCCESS';
export let CONNECT_WEB_SOCKET_FAIL = 'CONNECT_WEB_SOCKET_FAIL';
export let SET_ONLINE_COUNT = 'SET_ONLINE_COUNT';
